version: 0.2
env:
  variables:
    REGION: us-west-2
    VERSION: "1"

phases:
  install:
    commands:
      - echo "Installing AWS CLI..."
      - yum update -y && yum install -y awscli
    on-failure: ABORT
    runtime-versions:
      nodejs: 20
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo "Granting execute permissions to deploy.sh..."
      - chmod +x $CODEBUILD_SRC_DIR/deploy.sh
      - echo "Building..."
      - $CODEBUILD_SRC_DIR/deploy.sh